SELECT SYSDATE FROM DUAL ;


SELECT TABLE_NAME, OWNER
FROM ALL_TABLES
WHERE OWNER = 'WILSON';

SELECT * FROM WILSON.COURS ;


EXEC P_AJOUT_COURS('9MAT154', 'CALCULS avances', 125,NULL, 3,6,3);


INSERT INTO WILSON.COURS (SIGLE_COURS, TITRE_COURS, NRO_DEPARTEMENT, RESP_COURS)
VALUES('9mat458', 'CALCULS AVANCES', 125, 'PAB350');

SELECT * FROM WILSON.ENSEIGNANT ;

INSERT INTO WILSON.ENSEIGNANT(MATRICULE_ENSEIGNANT, PRENOM, NOM, NRO_DEPARTEMENT,STATUT)
VALUES('STEBAL14', 'STEPHANIE', 'BALLA', '300', '3');


SELECT * FROM WILSON.VUE_DEPARTEMENT ;

SELECT * FROM WILSON.VUE_COURS ;
