ALTER SESSION SET CONTAINER = XEPDB1;



/*
Username : wilson
Password : uqac2025
Service Name : XEPDB1
*/

/* GRANTS (déjà faits)
GRANT CREATE SESSION TO wilson;
GRANT CREATE TABLE TO wilson;
GRANT CREATE SEQUENCE TO wilson;
GRANT CREATE TRIGGER TO wilson;
GRANT CREATE VIEW TO wilson;
GRANT CREATE PROCEDURE TO wilson;
*/

----------------------------------------------------------------------------------------------
-- DROP TABLES ET SEQUENCES EXISTANTES
----------------------------------------------------------------------------------------------

DROP TABLE WILSON.INSCRIPTION ;
DROP TABLE WILSON.PLANIFICATION ;
DROP TABLE WILSON.COURS_ENSEIGNE ;
DROP TABLE WILSON.COURS_PREALABLE ;
DROP TABLE WILSON.COURS ;
DROP TABLE WILSON.DIRECTEUR_DEPARTEMENT ;
DROP TABLE WILSON.ENSEIGNANT ;
DROP TABLE WILSON.ETUDIANT ;
DROP TABLE WILSON.DEPARTEMENT ;
DROP TABLE WILSON.ADRESSE_PERSONNE ;
DROP TABLE PERSONNE ;
DROP TABLE WILSON.LOCAL ;


DROP SEQUENCE WILSON.SEQ_NRO_ID_PREALABLE;
DROP SEQUENCE WILSON.SEQ_ID_LOCAL;
DROP SEQUENCE WILSON.SEQ_ID_PERSONNE;
DROP SEQUENCE WILSON.SEQ_ID_ADRESSE_PERSONNE;
DROP SEQUENCE WILSON.SEQ_ID_ENSEIGNANT;
DROP SEQUENCE WILSON.SEQ_ID_ETUDIANT;
DROP SEQUENCE WILSON.SEQ_ID_DEPARTEMENT;
DROP SEQUENCE WILSON.SEQ_ID_DIR_DPT;
DROP SEQUENCE WILSON.SEQ_ID_COURS;
DROP SEQUENCE WILSON.SEQ_ID_PLANIFICATION;
DROP SEQUENCE WILSON.SEQ_ID_INSCRIPTION;

----------------------------------------------------------------------------------------------
-- CREATION DES TABLES ET SEQUENCES
----------------------------------------------------------------------------------------------

-- LOCAL
CREATE SEQUENCE SEQ_ID_LOCAL START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE LOCAL(
    ID_LOCAL NUMBER PRIMARY KEY ,
    NRO_LOCAL VARCHAR2(10) UNIQUE NOT NULL,
    NOM_LOCAL VARCHAR2(30) UNIQUE ,
    CAPACITE NUMBER(3),
    CONSTRAINT CHK_DOMAINE_NRO_LOCAL CHECK (
        REGEXP_LIKE(NRO_LOCAL, '^[A-G][0-9]-[1-4][0-9]{3}$')
    )
);

-- PERSONNE
CREATE SEQUENCE SEQ_ID_PERSONNE START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE PERSONNE(
    ID_PERSONNE NUMBER PRIMARY KEY,
    NAS NUMBER(9) UNIQUE NOT NULL,
    PRENOM VARCHAR2(30) NOT NULL,
    NOM VARCHAR2(30) NOT NULL,
    DATE_NAISSANCE DATE,
    COURRIEL_PERSONNEL VARCHAR2(50),
    TEL VARCHAR2(10)
);

-- ADRESSE_PERSONNE
CREATE SEQUENCE SEQ_ID_ADRESSE_PERSONNE START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE ADRESSE_PERSONNE(
    ID_ADRESSE NUMBER PRIMARY KEY, 
    ADRESSE_CIVIQUE VARCHAR2(50) NOT NULL,
    NAS NUMBER(9) UNIQUE,
    CONSTRAINT FK_ADRESSE_PERSONNE FOREIGN KEY (NAS)
        REFERENCES PERSONNE(NAS)
        ON DELETE SET NULL
);

-- DEPARTEMENT
CREATE SEQUENCE SEQ_ID_DEPARTEMENT START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE DEPARTEMENT(
    ID_DEPARTEMENT NUMBER PRIMARY KEY,
    NRO_DEPARTEMENT NUMBER(3) UNIQUE NOT NULL,
    NOM_DEPARTEMENT VARCHAR2(50) NOT NULL UNIQUE
);


-- ENSEIGNANT
CREATE SEQUENCE SEQ_ID_ENSEIGNANT START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE ENSEIGNANT (
    ID_ENSEIGNANT NUMBER PRIMARY KEY,
    MATRICULE_ENSEIGNANT VARCHAR2(10) UNIQUE NOT NULL,
    NAS NUMBER(9) UNIQUE,
    PRENOM VARCHAR2(30) NOT NULL,
    NOM VARCHAR2(30) NOT NULL,
    NRO_DEPARTEMENT NUMBER(3),
    COURRIEL_PRO VARCHAR2(70) UNIQUE,
    STATUT CHAR(1),
    DATE_EMBAUCHE DATE DEFAULT SYSDATE,
    NRO_LOCAL VARCHAR2(10),
    POSTE CHAR(4),
    ANCIENNETE NUMBER,
    CONSTRAINT FK_LOCAL FOREIGN KEY (NRO_LOCAL)
        REFERENCES LOCAL(NRO_LOCAL)
        ON DELETE SET NULL,
    CONSTRAINT CHK_DOM_POSTE CHECK(REGEXP_LIKE(POSTE, '^[0-9]{4}$')),
    CONSTRAINT CHK_DOM_STATUT_ENS CHECK (STATUT IN ('0','1','2','3','4')),
    CONSTRAINT FK_NAS_ENS FOREIGN KEY (NAS)
        REFERENCES PERSONNE (NAS)
        ON DELETE SET NULL,
    CONSTRAINT FK_DEPARTEMENT FOREIGN KEY(NRO_DEPARTEMENT)
        REFERENCES DEPARTEMENT(NRO_DEPARTEMENT)
        ON DELETE SET NULL
);

-- TRIGGER COURRIEL PROFESSIONNEL ENSEIGNANT

CREATE OR REPLACE TRIGGER TRG_GENERER_COURRIEL_PRO_ENS
BEFORE INSERT ON ENSEIGNANT
FOR EACH ROW
DECLARE
    NOMBRE_ENSEIGNANTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO NOMBRE_ENSEIGNANTS FROM ENSEIGNANT
        WHERE LOWER(PRENOM) = LOWER(:NEW.PRENOM)AND LOWER(NOM) = LOWER(:NEW.NOM);
    IF NOMBRE_ENSEIGNANTS = 0 THEN
        :NEW.COURRIEL_PRO := LOWER(:NEW.PRENOM) || '_' || LOWER(:NEW.NOM) || '@uqac.ca';
    ELSE
        :NEW.COURRIEL_PRO := LOWER(:NEW.PRENOM) || '_' || LOWER(:NEW.NOM) || TO_CHAR(NOMBRE_ENSEIGNANTS+1) || '@uqac.ca';
    END IF;
END;
/


-- TRIGGER ANCIENNETE ENSEIGNANT
CREATE OR REPLACE TRIGGER TRG_ANCIENNETE
BEFORE INSERT OR UPDATE ON ENSEIGNANT
FOR EACH ROW
BEGIN
    IF :NEW.DATE_EMBAUCHE IS NOT NULL THEN
        :NEW.ANCIENNETE := ROUND(MONTHS_BETWEEN(SYSDATE, :NEW.DATE_EMBAUCHE) / 12, 2);
    ELSE
        :NEW.ANCIENNETE := NULL;
    END IF;
END;
/

-- ETUDIANT
CREATE SEQUENCE SEQ_ID_ETUDIANT START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE ETUDIANT(
    ID_ETUDIANT NUMBER PRIMARY KEY,
    CODE_PERMANENT VARCHAR2(10) UNIQUE NOT NULL,
    PRENOM VARCHAR2(30) NOT NULL,
    NOM VARCHAR2(30) NOT NULL,
    DATE_INSCRIPTION_PROGRAMME DATE DEFAULT SYSDATE,
    DATE_NAISSANCE DATE,
    COURRIEL_PRO VARCHAR2(70) UNIQUE,
    STATUT CHAR(1),
    NAS NUMBER(9) UNIQUE,
    CONSTRAINT FK_NAS_ETU FOREIGN KEY (NAS)
        REFERENCES PERSONNE(NAS)
        ON DELETE SET NULL,
    CONSTRAINT CHK_STATUT_ETU CHECK(STATUT IN ('c','A','T','S','P'))
);

-- TRIGGER COURRIEL PROFESSIONNEL ETUDIANT

CREATE OR REPLACE TRIGGER TRG_GENERER_COURRIEL_PRO_ETU
BEFORE INSERT ON ETUDIANT
FOR EACH ROW
DECLARE
    NOMBRE_ETUDIANTS NUMBER;
BEGIN
    SELECT COUNT(*) INTO NOMBRE_ETUDIANTS FROM ETUDIANT
        WHERE LOWER(PRENOM) = LOWER(:NEW.PRENOM)AND LOWER(NOM) = LOWER(:NEW.NOM);
    IF NOMBRE_ETUDIANTS = 0 THEN
        :NEW.COURRIEL_PRO := LOWER(:NEW.PRENOM) || '_' || LOWER(:NEW.NOM) || '@uqac.ca';
    ELSE
        :NEW.COURRIEL_PRO := LOWER(:NEW.PRENOM) || '_' || LOWER(:NEW.NOM) || TO_CHAR(NOMBRE_ETUDIANTS+1) || '@etu.uqac.ca';
    END IF;
END;
/



-- DIRECTEUR_DEPARTEMENT
CREATE SEQUENCE SEQ_ID_DIR_DPT START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE DIRECTEUR_DEPARTEMENT(
    ID_DIR_DPT NUMBER,
    NRO_DEPARTEMENT NUMBER(3) NOT NULL,
    MATRICULE_DIRECTEUR VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_DIR_DIRECTEUR_DPT FOREIGN KEY(MATRICULE_DIRECTEUR)
        REFERENCES ENSEIGNANT(MATRICULE_ENSEIGNANT)
        ON DELETE CASCADE,
    CONSTRAINT FK_DPT_DIR_DPT FOREIGN KEY(NRO_DEPARTEMENT)
        REFERENCES DEPARTEMENT(NRO_DEPARTEMENT)
        ON DELETE CASCADE
);

-- COURS
CREATE SEQUENCE SEQ_ID_COURS START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE COURS (
    ID_COURS NUMBER PRIMARY KEY,
    SIGLE_COURS VARCHAR2(10) UNIQUE NOT NULL,
    TITRE_COURS VARCHAR2(60),
    NRO_DEPARTEMENT NUMBER(3),
    RESP_COURS VARCHAR2(10),
    NBR_CREDITS NUMBER(2) DEFAULT 3,
    HEURES_THEORIQUES NUMBER(3) DEFAULT 3,
    HEURE_PERSO NUMBER(3) DEFAULT 6,
    CONSTRAINT CHK_DOM_SIGLE_COURS CHECK (
        REGEXP_LIKE(SIGLE_COURS, '^[0-9][A-Z]{3}[0-9]{3}$')
    ),
    CONSTRAINT CHK_DOM_NBR_CREDITS CHECK (NBR_CREDITS > 0),
    CONSTRAINT FK_NRO_DPT FOREIGN KEY (NRO_DEPARTEMENT)
        REFERENCES DEPARTEMENT(NRO_DEPARTEMENT)
        ON DELETE SET NULL,
    CONSTRAINT FK_RESP_COURS FOREIGN KEY (RESP_COURS)
        REFERENCES ENSEIGNANT(MATRICULE_ENSEIGNANT)
        ON DELETE SET NULL
);

-- COURS_PREALABLE
CREATE SEQUENCE SEQ_NRO_ID_PREALABLE START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE COURS_PREALABLE(
    ID_PREALABLE VARCHAR2(20) PRIMARY KEY,
    SIGLE_COURS VARCHAR2(10) NOT NULL,
    SIGLE_PREALABLE VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_SIGLE_COURS FOREIGN KEY (SIGLE_COURS)
         REFERENCES COURS(SIGLE_COURS)
         ON DELETE CASCADE,
    CONSTRAINT FK_SIGLE_PREALABLE FOREIGN KEY(SIGLE_PREALABLE)
        REFERENCES COURS(SIGLE_COURS)
        ON DELETE CASCADE
);

-- Trigger ID_PREALABLE
CREATE OR REPLACE TRIGGER TRG_ID_PREALABLE
BEFORE INSERT OR UPDATE ON COURS_PREALABLE
FOR EACH ROW
DECLARE
   NRO_ID NUMBER;
BEGIN
     NRO_ID := SEQ_NRO_ID_PREALABLE.NEXTVAL;
     :NEW.ID_PREALABLE := :NEW.SIGLE_COURS || '-' || :NEW.SIGLE_PREALABLE || '-' || TO_CHAR(NRO_ID);
END;
/

-- COURS_ENSEIGNE
CREATE TABLE COURS_ENSEIGNE(
    SIGLE_COURS VARCHAR2(10) NOT NULL,
    MATRICULE_ENSEIGNANT VARCHAR2(10) NOT NULL,
    GROUPE CHAR(2) NOT NULL,
    SESSION_COURS VARCHAR2(10) NOT NULL,
    NBR_ETUDIANTS NUMBER(3),
    CONSTRAINT PK_COURS_ENS PRIMARY KEY(SIGLE_COURS, MATRICULE_ENSEIGNANT, GROUPE, SESSION_COURS),
    CONSTRAINT FK_ENS FOREIGN KEY(MATRICULE_ENSEIGNANT)
        REFERENCES ENSEIGNANT(MATRICULE_ENSEIGNANT)
        ON DELETE CASCADE,
    CONSTRAINT FK_SIGLE_COURS_ENS FOREIGN KEY (SIGLE_COURS)
        REFERENCES COURS(SIGLE_COURS)
        ON DELETE CASCADE,
    CONSTRAINT NBR_MIN_ETU CHECK (NBR_ETUDIANTS >= 8),
    CONSTRAINT CHK_DOM_SESSION CHECK (
         REGEXP_LIKE(SESSION_COURS, '^20[0-9]{2}[1-3]$')
    ),
    CONSTRAINT CHK_DOM_GROUPE CHECK (
        REGEXP_LIKE(GROUPE, '^[0-9][0-9]$') AND GROUPE <> '00'
    )
);

-- PLANIFICATION
CREATE SEQUENCE SEQ_ID_PLANIFICATION START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE PLANIFICATION(
    ID_PLANIF NUMBER PRIMARY KEY,
    SIGLE_COURS VARCHAR2(10) NOT NULL,
    JOUR VARCHAR2(10) NOT NULL,
    HEURE_DEBUT VARCHAR2(10) NOT NULL,
    HEURE_FIN VARCHAR2(10) NOT NULL,
    NRO_LOCAL VARCHAR2(10) NOT NULL,
    ACTIVITE VARCHAR2(30),
    CONSTRAINT FK_SIGLE_COURS_PLAN FOREIGN KEY (SIGLE_COURS)
        REFERENCES COURS(SIGLE_COURS)
        ON DELETE CASCADE,
    CONSTRAINT FK_LOCAL_COURS_PLAN FOREIGN KEY (NRO_LOCAL)
        REFERENCES LOCAL(NRO_LOCAL)
        ON DELETE CASCADE,
    CONSTRAINT CHK_DOM_JOUR_PLAN CHECK(
        JOUR IN ('LUNDI', 'MARDI', 'MERCREDI','JEUDI', 'VENDREDI', 'SAMEDI')
    ),
    CONSTRAINT CHK_DOM_ACTIVITE_PLAN CHECK(
        ACTIVITE IN ('ENSEIGNEMENT', 'LABORATOIRE', 'TP', 'PRESENTATION', 'IMMERSION ENTREPRISE', 'AUTRE')
    ),
    CONSTRAINT CHK_FORMAT_HEURE_DEBUT CHECK(
        REGEXP_LIKE(HEURE_DEBUT, '^(?:[01]\d|2[0-3]):[0-5]\d$')
    ),
    CONSTRAINT CHK_FORMAT_HEURE_FIN CHECK(
        REGEXP_LIKE(HEURE_FIN, '^[0-2][0-9]:[0-5][0-9]$')
    ),
    CONSTRAINT CHK_FIN_SUP_DEBUT CHECK(
        REPLACE(HEURE_FIN, ':', '') > REPLACE(HEURE_DEBUT, ':', '')
    ),
    CONSTRAINT CHK_DOM_HEURE_DEBUT_INSC CHECK(
        REGEXP_LIKE(HEURE_DEBUT, '^[0-9][0-9]:[0-9][0-9]$')
    ),
    CONSTRAINT CHK_DOM_HEURE_FIN_INSC CHECK(
        REGEXP_LIKE(HEURE_FIN, '^[0-9][0-9]:[0-9][0-9]$')
    )
);

-- INSCRIPTION
CREATE SEQUENCE SEQ_ID_INSCRIPTION START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE INSCRIPTION(
    ID_INSCRIPTION NUMBER PRIMARY KEY,
    CODE_PERMANENT VARCHAR2(10) NOT NULL,
    SIGLE_COURS VARCHAR2(10) NOT NULL,
    DATE_INSCRIPTION DATE DEFAULT SYSDATE,
    STATUT VARCHAR2(2),
    CONSTRAINT FK_CODE_PERMANENT_INSCRIPTION FOREIGN KEY (CODE_PERMANENT)
        REFERENCES ETUDIANT(CODE_PERMANENT)
        ON DELETE CASCADE,
    CONSTRAINT FK_SIGLE_COURS_INSCRIPTION FOREIGN KEY(SIGLE_COURS)
        REFERENCES COURS(SIGLE_COURS)
        ON DELETE CASCADE,
    CONSTRAINT CHK_DOM_STATUT_INSC CHECK(
        STATUT IN ('A+','A','A-','B+','B','B-','C+','C','C-','D+','D','E','I', 'Y', 'Z')   
    )
);

----------------------------------------------------------------------------------------------
-- TRIGGERS UPDATE CASCADE
----------------------------------------------------------------------------------------------

-- NAS PERSONNE --> ENSEIGNANT ET ETUDIANT
CREATE OR REPLACE TRIGGER TRG_UPDATE_NAS
AFTER UPDATE OF NAS ON PERSONNE
FOR EACH ROW
BEGIN
    UPDATE ENSEIGNANT
    SET NAS = :NEW.NAS
    WHERE NAS = :OLD.NAS;
    
    UPDATE ETUDIANT
    SET NAS = :NEW.NAS
    WHERE NAS = :OLD.NAS;
END;
/

-- NRO_LOCAL LOCAL ? ENSEIGNANT & PLANIFICATION
CREATE OR REPLACE TRIGGER TRG_UPDATE_NRO_LOCAL_ENS
AFTER UPDATE OF NRO_LOCAL ON WILSON.LOCAL
FOR EACH ROW
BEGIN
    UPDATE WILSON.ENSEIGNANT
    SET NRO_LOCAL = :NEW.NRO_LOCAL
    WHERE NRO_LOCAL = :OLD.NRO_LOCAL;
    
    UPDATE WILSON.PLANIFICATION
    SET NRO_LOCAL = :NEW.NRO_LOCAL
    WHERE NRO_LOCAL = :OLD.NRO_LOCAL;
END;
/

-- MATRICULE_ENSEIGNANT --> COURS, COURS_ENSEIGNE, DIRECTEUR_DEPARTEMENT
CREATE OR REPLACE TRIGGER TRG_UPDATE_MAT_ENS_COURS
AFTER UPDATE OF MATRICULE_ENSEIGNANT ON WILSON.ENSEIGNANT
FOR EACH ROW
BEGIN
    UPDATE WILSON.COURS
    SET RESP_COURS = :NEW.MATRICULE_ENSEIGNANT
    WHERE RESP_COURS = :OLD.MATRICULE_ENSEIGNANT;
  -------------------------------------------------
    UPDATE WILSON.COURS_ENSEIGNE
    SET MATRICULE_ENSEIGNANT = :NEW.MATRICULE_ENSEIGNANT
    WHERE MATRICULE_ENSEIGNANT = :OLD.MATRICULE_ENSEIGNANT;

  ----------------------------------------------------------
    UPDATE WILSON.DIRECTEUR_DEPARTEMENT
    SET MATRICULE_DIRECTEUR = :NEW.MATRICULE_ENSEIGNANT
    WHERE MATRICULE_DIRECTEUR = :OLD.MATRICULE_ENSEIGNANT;
END;
/

-- SIGLE_COURS ? COURS_PREALABLE
CREATE OR REPLACE TRIGGER TRG_UPDATE_SIGLE_COURS_PREALABLE
AFTER UPDATE OF SIGLE_COURS ON COURS
FOR EACH ROW
BEGIN
    UPDATE WILSON.COURS_PREALABLE
    SET SIGLE_COURS = :NEW.SIGLE_COURS
    WHERE SIGLE_COURS = :OLD.SIGLE_COURS;

    UPDATE WILSON.COURS_PREALABLE
    SET SIGLE_PREALABLE = :NEW.SIGLE_COURS
    WHERE SIGLE_PREALABLE = :OLD.SIGLE_COURS;
END;
/

-- SIGLE_COURS --> COURS_ENSEIGNE, PLANIFICATION, INSCRIPTION
CREATE OR REPLACE TRIGGER TRG_UPDATE_SIGLE_COURS_ENS
AFTER UPDATE OF SIGLE_COURS ON WILSON.COURS
FOR EACH ROW
BEGIN
    UPDATE WILSON.COURS_ENSEIGNE
    SET SIGLE_COURS = :NEW.SIGLE_COURS
    WHERE SIGLE_COURS = :OLD.SIGLE_COURS;
    --------------------------------------
    UPDATE WILSON.PLANIFICATION
    SET SIGLE_COURS = :NEW.SIGLE_COURS
    WHERE SIGLE_COURS = :OLD.SIGLE_COURS;
    ---------------------------------------
    UPDATE WILSON.INSCRIPTION
    SET SIGLE_COURS = :NEW.SIGLE_COURS
    WHERE SIGLE_COURS = :OLD.SIGLE_COURS;
END;
/

----------------------------------------------------------------------------------------------
-- PROCEDURES STOCKEES
----------------------------------------------------------------------------------------------

-- AJOUT D'UN LOCAL

CREATE OR REPLACE PROCEDURE P_AJOUT_LOCAL (P_NRO_LOCAL IN VARCHAR2,P_NOM_LOCAL IN VARCHAR2,P_CAPACITE  IN NUMBER)IS
BEGIN
    INSERT INTO WILSON.LOCAL (ID_LOCAL, NRO_LOCAL, NOM_LOCAL, CAPACITE)
    VALUES (SEQ_ID_LOCAL.NEXTVAL, P_NRO_LOCAL, P_NOM_LOCAL, P_CAPACITE);
    COMMIT;
END P_AJOUT_LOCAL;
/



/*AJOUT D'UNE PERSONNE */
CREATE OR REPLACE PROCEDURE P_AJOUT_PERSONNE (P_NAS IN NUMBER,P_PRENOM  IN VARCHAR2,P_NOM IN VARCHAR2,P_DATE_NAISSANCE IN DATE,P_COURRIEL IN VARCHAR2,P_TEL IN VARCHAR2)IS
BEGIN
    INSERT INTO WILSON.PERSONNE (ID_PERSONNE, NAS, PRENOM, NOM, DATE_NAISSANCE, COURRIEL_PERSONNEL, TEL)
    VALUES (SEQ_ID_PERSONNE.NEXTVAL, P_NAS, P_PRENOM, P_NOM, P_DATE_NAISSANCE, P_COURRIEL, P_TEL);
    COMMIT;
END P_AJOUT_PERSONNE;
/

      
/*AJOUT D'UN ENSEIGNANT */
CREATE OR REPLACE PROCEDURE P_AJOUT_ENSEIGNANT(P_MATRICULE_ENSEIGNANT IN VARCHAR2, P_PRENOM IN VARCHAR2,P_NOM IN VARCHAR2, 
                                                P_NRO_LOCAL IN VARCHAR2 DEFAULT NULL, P_POSTE IN VARCHAR2 DEFAULT '1234',
                                                P_STATUT IN VARCHAR2 DEFAULT '1' , P_NRO_DEPARTEMENT IN NUMBER DEFAULT NULL) IS
BEGIN 
    INSERT INTO WILSON.ENSEIGNANT (ID_ENSEIGNANT,MATRICULE_ENSEIGNANT, PRENOM, NOM, NRO_LOCAL, POSTE,STATUT, NRO_DEPARTEMENT)
    VALUES (SEQ_ID_ENSEIGNANT.NEXTVAL, P_MATRICULE_ENSEIGNANT,P_PRENOM,P_NOM,P_NRO_LOCAL,P_POSTE, P_STATUT, P_NRO_DEPARTEMENT);
    COMMIT;
END P_AJOUT_ENSEIGNANT ;
/


/*AJOUT ETUDIANT*/

CREATE OR REPLACE PROCEDURE P_AJOUT_ETUDIANT (P_CODE_PERMANENT IN VARCHAR2,P_NOM IN VARCHAR2,P_PRENOM IN VARCHAR2,P_DATE_NAISSANCE IN DATE DEFAULT NULL) IS
BEGIN
    INSERT INTO WILSON.ETUDIANT (CODE_PERMANENT, PRENOM, NOM, DATE_NAISSANCE)
    VALUES (p_CODE_PERMANENT, P_PRENOM, P_NOM, P_DATE_NAISSANCE);
    COMMIT;
END P_AJOUT_ETUDIANT;
/


/*AJOUT D UN DEPARTEMENT*/

CREATE OR REPLACE PROCEDURE P_AJOUT_DEPARTEMENT(P_NRO_DEPARTEMENT IN NUMBER,P_NOM_DEPARTEMENT IN VARCHAR2 DEFAULT NULL)IS
BEGIN
    INSERT INTO WILSON.DEPARTEMENT (ID_DEPARTEMENT, NRO_DEPARTEMENT, NOM_DEPARTEMENT)
    VALUES (SEQ_ID_DEPARTEMENT.NEXTVAL, P_NRO_DEPARTEMENT, P_NOM_DEPARTEMENT);
    COMMIT;
END P_AJOUT_DEPARTEMENT;
/


 /*  AJOUT D UN COURS */
 
 CREATE OR REPLACE PROCEDURE P_AJOUT_COURS (P_SIGLE_COURS IN VARCHAR2,P_TITRE_COURS IN VARCHAR2,P_NRO_DEPARTEMENT IN NUMBER ,
                                            P_RESP_COURS IN VARCHAR2 DEFAULT NULL,P_NBR_CREDITS  IN NUMBER DEFAULT 3,
                                            P_HEURES_THEORIQUES IN NUMBER DEFAULT 6 ,P_HEURE_PERSO IN NUMBER DEFAULT 3) IS
BEGIN
    INSERT INTO WILSON.COURS (ID_COURS,SIGLE_COURS,TITRE_COURS, NRO_DEPARTEMENT, RESP_COURS, NBR_CREDITS, HEURES_THEORIQUES,HEURE_PERSO)
    VALUES (SEQ_ID_COURS.NEXTVAL,P_SIGLE_COURS,P_TITRE_COURS,P_NRO_DEPARTEMENT,P_RESP_COURS,P_NBR_CREDITS,P_HEURES_THEORIQUES,P_HEURE_PERSO);
    COMMIT;
END P_AJOUT_COURS;
/


CREATE OR REPLACE PROCEDURE P_AJOUT_PLANIF(P_SIGLE_COURS IN VARCHAR2, P_JOUR IN VARCHAR2, P_HEURE_DEBUT IN VARCHAR2, 
                                            P_HEURE_FIN IN VARCHAR2, P_NRO_LOCAL IN VARCHAR2, P_ACTIVITE IN VARCHAR2) IS
BEGIN 
    INSERT INTO WILSON.PLANIFICATION (ID_PLANIF,SIGLE_COURS,JOUR,HEURE_DEBUT, HEURE_FIN, NRO_LOCAL, ACTIVITE)
    VALUES (SEQ_ID_PLANIFICATION.NEXTVAL ,P_SIGLE_COURS,P_JOUR,P_HEURE_DEBUT, P_HEURE_FIN, P_NRO_LOCAL, P_ACTIVITE);
    COMMIT ; 
END P_AJOUT_PLANIF ;
/


CREATE OR REPLACE PROCEDURE P_AJOUT_INSCRIPTION(P_CODE_PERMANENT IN VARCHAR2, P_SIGLE_COURS IN VARCHAR2, P_STATUT IN VARCHAR2) IS
BEGIN 
    INSERT INTO WILSON.INSCRIPTION(ID_INSCRIPTION, CODE_PERMANENT, SIGLE_COURS, STATUT) VALUES 
    (SEQ_ID_INSCRIPTION.NEXTVAL, P_CODE_PERMANENT, P_SIGLE_COURS,P_STATUT);
    COMMIT ; 
END P_AJOUT_INSCRIPTION ;
/
